x=5
try:
    print("The number is {}".f(x))
except AttributeError:
    print("An error occurred.")